---
title: Curriculum Vitae
output:
  html_document:
    theme: united
    highlight: tango
    includes:
      after_body: footer.html
---
***
### À propos

#### Contact

+ Téléphone: 514.952.0327
+ Email: [jacob.taylor.01@gmail.com](mailto:jacob.taylor.01@gmail.com)
+ Site Web: [https://jacobtaylor.xyz](https://jacobtaylor.xyz)

#### Institutions

+ École secondaire Saint-Gabriel, Programme d'éducation international 2012 -- 2014
+ École secondaire Rive-Nord, Programme d'éducation international 2014 -- 2018
+ Collège Lionel-Groulx, Sciences informatiques mathématiques 2018 --

### Languages

#### Humaines

Anglais et espagnol (débutant).

#### Machine

Python, R, PHP, bash/shell (débutant), c#, languages de balissage incluant LaTeX, R Markdown, HTML et CSS.

### Programmes avec lesquels je suis familier

tmux, ssh, RStudio, Blender (mostly for video-editing), Praat, Audacity, E-Prime, GIMP, pandoc, Jupyter. I've managed websites manually via ssh and vim using HTML/CSS/PHP and with tools such as Github Pages (Jekyll) WordPress via either cpanel or wp-cli. Some experience with myBB.

### Bénévolat

#### Emballage à l'épicerie

+ Emballage à l'épicerie Super C de Terrebonne.
+ Emballage à l'épicerie Provigo à deux reprises.

#### Soutient aux personnes dans le besoin

+ Multiples guignolées pour la ville de Sainte-Anne-des-Plaines
+ Aide aux personnes agées atteintent de l'Alhzymer dans le centre ... 
+ Rammasser les feuilles en automne avec l'organisme Petit Peuple, à Blainville.

***