---
title: "Jacob Taylor"
output:
  prettydoc::html_pretty:
    theme: caymen
    css: style.css
    highlight: github
    math: katex
---
# Articles <i class="fa fa-newspaper-o"></i>

***

- [Installation de ``base`` de Arch Linux](articles/arch_install.html)

- [Installation de Arch Linux sur ``LVM``](articles/arch_install_lvm.html)

- [Installation de Arch ``encrypté sur LVM``](articles/arch_install_lvm_encrypt.html)

[Plus d'articles](articles/articles.html) <i class="fa fa-angle-right"></i>

# Projets <i class="fa fa-code"></i>

***

La plupart de mes projets sont disponibles sur mon [Github](https://github.com/jacobtaylor27).

+ [Battleship 3D](projets/battleship.html)

+ [Jeu ``Snake``](projets/snake.html)

+ [Jeu ``Pong``](projets/pong.html)

[Plus de projets](projets/projets.html) <i class="fa fa-angle-right"></i>

# Fichiers <i class="fa fa-file-text-o"></i>

***

+ [Ensemble des ``dotfiles``](https://github.com/jacobtaylor27)

+ [Configuration de ``i3wm``](fichiers/i3wm.html)

+ [.bashrc](fichiers/bashrc.html)

[Plus de fichiers](fichiers/fichiers.html) <i class="fa fa-angle-right"></i>

# Outils <i class="fa fa-laptop"></i>

***

+ Brave Browser

+ Visual Studio

+ Dell XPS 13

[Plus d'outils](outils/outils.html) <i class="fa fa-angle-right"></i>

# Me rejoindre <i class="fa fa-envelope-o"></i>

***

Pour me rejoindre, il est possible de m'écrire par courriel à l'adresse suivante : jacob@jacobtaylor.xyz ou sur n'importe quel de mes réseaux sociaux.

<nav>
  <ul>
    <li> <a href="https://twitter.com/57JacobTaylor" target="_blank"><i class="fa fa-twitter" ></i></a> </li>
    <li><a href="https://www.instagram.com/jacobtaylorvsm/" target="_blank"><i class="fa fa-instagram" ></i></a> </li>
    <li><a href="https://open.spotify.com/user/31bygrnvenhfovhunk4mvtqdrht4?si=oXeg9RVfQZ2laUha4qXxhw" target="_blank"><i class="fa fa-spotify"></i></a> </li>
    <li><a href="https://github.com/jacobtaylor27" target="_blank"><i class="fa fa-github"></i> </a> </li>
    <li><a href="https://www.snapchat.com/add/jakkyboy27" target="_blank"><i class="fa fa-snapchat"></i></a> </li>
    <li><a href="https://www.reddit.com/user/jtaylor27/" target="_blank"><i class="fa fa-reddit"></i></a> </li>
    <li><a href="https://www.linkedin.com/in/jacob-t-1a570aba/" target="_blank"><i class="fa fa-linkedin"></i></a> </li>
  </ul>
</nav>

<center style="font-size:16px;">
  <i class="fa fa-clock-o"></i> Mis à jour le `r format(Sys.time(), '%d avril %Y')`

  <div style="margin-top:0px;">
  <i class="fa fa-user-o"></i> Jacob Taylor
  <p id="count">0</p>
  </div>
</center>

<script src="count.js"></script>
<link rel="icon" href="https://www.freefavicon.com/freefavicons/objects/jack-of-spades-152-192574.png">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


