---
title: "Meilleurs séries télé"
author: "par Jacob Taylor"
date: "`r format(Sys.time(), '%d avril %Y')`"
output:
  prettydoc::html_pretty:
    theme: caymen
    css: style.css
    highlight: github
    math: katex
---
# Meilleurs séries télé <i class="fa fa-tv"></i>

*** 

Tout ces choix sont personnels en fonction de mon appréciation de la série télé et non des critiques *rotten tomatoes* ou *imdb*. Cette liste est également classé par **ordre alphabétique** et non par ordre de préférence.

### Broadchurch (2013 - 2017)

> Le meurtre d'un jeune garçon à Broadchurch, une petite ville côtière, entraine un déferlement médiatique qui menace de déchirer les liens de sa communauté.

**Nombre de saisons** : 3

**Nombre d'épisodes** : 24

**Durée** : 46m

**Créateur** : Chris Chibnall

**Tête d'affiche** : David Tennant, Olivia Colman, Jodie Whittaker, Andrew Buchan

### Brooklyn Nine-Nine (2013 - actuel)

> La vie au sein du commissariat de police de Brooklyn n'est pas de tout repos : une pléiade d'inspecteurs un poil loufoques doivent jongler entre leur mission de protéger et servir les habitants de la ville, leur vie personnelle et surtout celle du bureau.

**Nombre de saisons** : 7

**Nombre d'épisodes** : 137

**Durée** : 23m

**Créateur** : Micheal Schur

**Tête d'affiche** : Andy Samberg, Melissa Fumero, Terry Crews, Joe Lo Truglio, Stephamie Beatriz, Andre Braugher

### How I Met Your Mother (2005 - 2014)

> Ted se remémore ses jeunes années, lorsqu'il était encore célibataire. Il raconte à ses enfants avec nostalgie ses moments d'égarements et de troubles, ses rencontres et ses recherches effrénées du Grand Amour et les facéties de sa bande d'amis...

**Nombre de saisons** : 9

**Nombre d'épisodes** : 208

**Durée** : 22m

**Créateur** : Carter Bays

**Tête d'affiche** : Josh Radnor, Jason Segel, Cobie Smulders, Neil Patrick Harris, Alyson Hannigan

### Merlin (2008 - 2012)

> Dans la mythique cité de Camelot, certaines histoires se racontent comme on le fait aujourd'hui, au XXIème siècle. Entre enchantements et mystères, c'est là qu'un jeune homme nommé Merlin se lie d'amitié avec un certain Arthur...

**Nombre de saisons** : 5

**Nombre d'épisodes** : 65

**Durée** : 43m

**Créateur** : Julian Jones

**Tête d'affiche** : Colin Morgan, Bradley James, Katie McGrath, Richard Wilson, Angel Coulby, Anthony Stewart Head

### The Office (2005 - 2013)

> Ce faux documentaire (mockumentary) raconte le quotidien d'un groupe d'employés de bureau dans une fabrique de papier en Pennsylvanie. Michael, le responsable régional, pense être le mec le plus drôle du bureau. Il ne se doute pas que ses employés le tolèrent uniquement parce que c'est lui qui signe les chèques. S'efforçant de paraître cool et apprécié de tous, Michael est en fait perçu comme étant pathétique...

**Nombre de saisons** : 9

**Nombre d'épisodes** : 188

**Durée** : 20m

**Créateur** : Ricky Gervais

**Tête d'affiche** : Steve Carell, Rainn Wilson, John Krasinski, Jenna Fischer, B.J. Novak, Ed Helms

### Prison Break (2005 - 2017)

> Michael Scofield s'engage dans une véritable lutte contre la montre : son frère Lincoln est dans le couloir de la mort, en attente de son exécution. Persuadé de son innocence mais à court de solutions, Michael décide de se faire incarcérer à son tour dans le pénitencier d'état de Fox River pour organiser leur évasion...

**Nombre de saisons** : 5

**Nombre d'épisodes** : 90

**Durée** : 45m

**Créateur** : Paul Scheuring

**Tête d'affiche** : Wentworth Miller, Dominic Percell, Robert Knepper, Amaury Nolasco, Sarah Wayne Callies, William Fichtner

### Sherlock (2010 - actuel)

> Les aventures modernisées du plus célèbre des enquêteurs : Sherlock Holmes et de son ami et assistant, le Dr Watson. Un remake vivant et drôle du classique de Arthur Conan Doyle revisité par Steven Moffat.

**Nombre de saisons** : 4

**Nombre d'épisodes** : 13

**Durée** : 1h 30m

**Créateur** : Mark Gatiss

**Tête d'affiche** : Benedict Cumberbatch, Martin Freeman, Rupert Graves, Mark Gatiss, Andrew Scott, Louise Brealy

### The Simpsons (1989 - actuel)

> Les Simpson, famille américaine moyenne, vivent à Springfield. Homer, le père, a deux passions : regarder la télé et boire des bières. Mais son quotidien est rarement reposant, entre son fils Bart qui fait toutes les bêtises possibles, sa fille Lisa qui est une surdouée, ou encore sa femme Marge qui ne supporte pas de le voir se soûler à longueur de journée.

**Nombre de saisons** : 30

**Nombre d'épisodes** : 678

**Durée** : 22m

**Créateur** : Matt Groening

**Tête d'affiche** : Dan Catellaneta, Julie Kavner, Nancy Cartwright, Yeardly Smith

***

<nav >
  <ul style="margin-bottom:0px;">
    <li> <a href="https://twitter.com/57JacobTaylor" target="_blank"><i class="fa fa-twitter" ></i></a> </li>
    <li><a href="https://www.instagram.com/jacobtaylorvsm/" target="_blank"><i class="fa fa-instagram" ></i></a> </li>
    <li><a href="https://open.spotify.com/user/31bygrnvenhfovhunk4mvtqdrht4?si=oXeg9RVfQZ2laUha4qXxhw" target="_blank"><i class="fa fa-spotify"></i></a> </li>
    <li><a href="https://github.com/jacobtaylor27" target="_blank"><i class="fa fa-github"></i> </a> </li>
    <li><a href="https://www.snapchat.com/add/jakkyboy27" target="_blank"><i class="fa fa-snapchat"></i></a> </li>
    <li><a href="https://www.reddit.com/user/jtaylor27/" target="_blank"><i class="fa fa-reddit"></i></a> </li>
    <li><a href="https://www.linkedin.com/in/jacob-t-1a570aba/" target="_blank"><i class="fa fa-linkedin"></i></a> </li>
  </ul>
</nav>

<center style="font-size:16px; margin-top:0px;">
  <i class="fa fa-clock-o"></i> Mis à jour le `r format(Sys.time(), '%d avril %Y')`

  <div style="margin-top:0px;">
  <i class="fa fa-user-o"></i> Jacob Taylor
  </div>
</center>

<link rel="icon" href="https://www.freefavicon.com/freefavicons/objects/jack-of-spades-152-192574.png">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">