---
title: "Meilleurs films"
author: "par Jacob Taylor"
date: "`r format(Sys.time(), '%d avril %Y')`"
output:
  prettydoc::html_pretty:
    theme: caymen
    css: style.css
    highlight: github
    math: katex
---
# Meilleurs films et séries de films <i class="fa fa-film"></i>

***

Tout ces choix sont personnels en fonction de mon appréciation du film ou de la série de films et non des critiques sur *rotten tomatoes* ou *imdb*. Cette liste est également classé par **ordre alphabétique** et non par ordre de préférence.

### The Dark Knight (2008)

> Dans ce nouveau volet, Batman augmente les mises dans sa guerre contre le crime. Avec l'appui du lieutenant de police Jim Gordon et du procureur de Gotham, Harvey Dent, Batman vise à éradiquer le crime organisé qui pullule dans la ville. Leur association est très efficace mais elle sera bientôt bouleversée par le chaos déclenché par un criminel extraordinaire que les citoyens de Gotham connaissent sous le nom de Joker.

**Directeur** : Christopher Nolan

**Durée** : 2h 27m

**Tête d'affiche** : Christian Bale, Micheal Caine, Heath Ledger, Gary Oldman

### Gone Girl (2014)

> Amy et Nick forment en apparence un couple modèle. Victimes de la crise, ils quittent Manhattan pour retourner s’installer dans la ville du Missouri où Nick a grandi. Mais le jour de leur 5ème anniversaire de mariage, Amy disparaît et Nick retrouve leur maison saccagée. Lors de l’enquête tout semble accuser Nick. Celui-ci décide, de son côté, de tout faire pour savoir ce qui est arrivé à Amy et découvre qu’elle lui dissimulait beaucoup de choses.

**Directeur** : David Fincher

**Durée** : 2h 25m

**Tête d'affiche** : Ben Affleck, Rosamund Pike, Neil Patrick Harris

### Good Will Hunting (1997)

> Will Hunting est un authentique génie mais également un rebelle aux élans imprévisibles. Il est né dans le quartier populaire de South Boston et a arrêté très tôt ses études, refusant le brillant avenir que pouvait lui procurer son intelligence. Il vit désormais entouré d'une bande de copains et passe son temps dans les bars a chercher la bagarre et à commettre quelques petits délits qui risquent bien de l'envoyer en prison. C'est alors que ses dons prodigieux en mathématiques attirent l'attention du professeur Lambeau, du Massachusetts Institute of Technology...

**Directeur** : Gus Van Sant

**Durée** : 2h 06m

**Tête d'affiche** : Matt Damon, Robin Williams, Ben Affleck, Stellan Skarsgard

### Harry Potter - Saga (2001, 2002, 2004, 2005, 2007, 2009, 2010, 2011)

> La saga Harry Potter narre les aventures d'un apprenti sorcier nommé Harry Potter et de ses amis Ron Weasley et Hermione Granger à l'école de sorcellerie Poudlard dirigée par Albus Dumbledore.

**Directeur** : Chris Columbus, David Yates, Alfonso Cuaron, Mike Newell

**Durée** : 2h 30m (en moyenne)

**Nombre de films** : 8

**Tête d'affiche** : Daniel Radcliffe, Emma Watson, Rupert Grint, Alan Rickman, Richard Harris, Micheal Gambon, Ralph Fiennes, Tom Felton, Gary Oldman

### The Imitation Game (2014)

> L'histoire hors-norme d'Alan Turing, le mathématicien anglais qui aida à percer le code de l'outil de communication des Allemands durant la Seconde Guerre mondiale : la machine Enigma.

**Directeur** : Morten Tyldum

**Durée** : 1h 55m

**Tête d'affiche** : Benedict Cumberbatch, Keira Knightley, Matthew Goode

### Interstellar (2014)

> Dans un futur proche, face à une Terre exsangue, un groupe d'explorateurs utilise un vaisseau interstellaire pour franchir un trou de ver permettant de parcourir des distances jusque-là infranchissables. Leur but : trouver un nouveau foyer pour l'humanité.

**Directeur** : Christopher Nolan

**Durée** : 2h 49m

**Tête d'affiche** : Matthew McConaughey, Jessica Chastain, Anne Hathaway, Michael Caine, Timothée Chalamet

### John Wick - Saga (2014, 2017, 2019, 2021)

> John Wick est un film d'action américain de 2014 dirigé par Chad Stahelski et David Leitch et interprété par Keanu Reeves, Michael Nyqvist, Alfie Allen, Adrianne Palicki, Bridget Moynahan, Dean Winters, Ian McShane, John Leguizamo et Willem Dafoe. L’acteur Reeves interprete John Wick, un soldat à la retraite qui cherche une vengeance pour le vol de sa voiture vintage et le meurtre de son chiot, un cadeau de sa femme récemment décédée. Stahelski et Leitch ont dirigé le film ensemble, bien que Leitch n'ait pas été crédité. Une suite, intitulée John Wick: chapitre 2, a été diffusée le 10 février 2017. Un troisième volet est en projet, toujours avec le réalisateur Chad Stahelski et le scénariste Derek Kolstad.

**Directeur** : Chad Stahelski 

**Durée** : 2h 00m (en moyenne)

**Nombre de films** : 4 (3 sortis)

**Tête d'affiche** : Keanu Reeves, Riccardo Scamarcio, Ian McShane, Laurence Fishburne, Willem Dafoe, Micheal Nyqvist

### Prisoners (2013)

> Dans la banlieue de Boston, deux fillettes de 6 ans, Anna et Joy, ont disparu. Le détective Loki privilégie la thèse du kidnapping suite au témoignage de Keller, le père d’Anna. Le suspect numéro 1 est rapidement arrêté mais est relâché quelques jours plus tard faute de preuve, entrainant la fureur de Keller. Aveuglé par sa douleur, le père dévasté se lance alors dans une course contre la montre pour retrouver les enfants disparus. De son côté, Loki essaie de trouver des indices pour arrêter le coupable avant que Keller ne commette l’irréparable… Les jours passent et les chances de retrouver les fillettes s’amenuisent…

**Directeur** : Denis Villeneuve

**Durée** : 2h 26m

**Tête d'affiche** : Hugh Jackman, Jake Gyllenhaal, Paul Dano, Maria Bello

### Shutter Island (2010)

> En 1954, le marshal Teddy Daniels et son coéquipier Chuck Aule sont envoyés enquêter sur l'île de Shutter Island, dans un hôpital psychiatrique où sont internés de dangereux criminels. L'une des patientes, Rachel Solando, a inexplicablement disparu. Comment la meurtrière a-t-elle pu sortir d'une cellule fermée de l'extérieur ? Le seul indice retrouvé dans la pièce est une feuille de papier sur laquelle on peut lire une suite de chiffres et de lettres sans signification apparente. Œuvre cohérente d'une malade, ou cryptogramme ?

**Directeur** : Martin Scorsese

**Durée** : 2h 18m

**Tête d'affiche** : Lenoardo DiCaprio, Mark Ruffalo, Ben Kingsley, Emily Mortimer

### The Simpsons : The Movie (2007)

> Lorsque Homer pollue gravement le lac de Springfield, une agence de protection de l'environnement décide de mettre la ville en quarantaine en l'isolant sous un énorme dôme. Les Springfieldiens, fous de rage, sont bien décidés à lyncher le coupable. Devant cette vague d'animosité, les Simpson n'ont d'autre choix que de fuir et de s'exiler en Alaska.

**Directeur** : David Silverman

**Durée** : 1h 30m

**Tête d'affiche** : Dan Catellaneta, Julie Kavner, Nancy Cartwright, Yeardly Smith

### The Wolf of Wall Street (2013)

> Lorsque Homer pollue gravement le lac de Springfield, une agence de protection de l'environnement décide de mettre la ville en quarantaine en l'isolant sous un énorme dôme. Les Springfieldiens, fous de rage, sont bien décidés à lyncher le coupable. Devant cette vague d'animosité, les Simpson n'ont d'autre choix que de fuir et de s'exiler en Alaska.

**Directeur** : Martin Scorsese

**Durée** : 2h 59m

**Tête d'affiche** : Leonardo DiCaprio, Jonah Hill, Margot Robbie, Matthew McConaughey, Jon Bernthal

***

<nav >
  <ul style="margin-bottom:0px;">
    <li> <a href="https://twitter.com/57JacobTaylor" target="_blank"><i class="fa fa-twitter" ></i></a> </li>
    <li><a href="https://www.instagram.com/jacobtaylorvsm/" target="_blank"><i class="fa fa-instagram" ></i></a> </li>
    <li><a href="https://open.spotify.com/user/31bygrnvenhfovhunk4mvtqdrht4?si=oXeg9RVfQZ2laUha4qXxhw" target="_blank"><i class="fa fa-spotify"></i></a> </li>
    <li><a href="https://github.com/jacobtaylor27" target="_blank"><i class="fa fa-github"></i> </a> </li>
    <li><a href="https://www.snapchat.com/add/jakkyboy27" target="_blank"><i class="fa fa-snapchat"></i></a> </li>
    <li><a href="https://www.reddit.com/user/jtaylor27/" target="_blank"><i class="fa fa-reddit"></i></a> </li>
    <li><a href="https://www.linkedin.com/in/jacob-t-1a570aba/" target="_blank"><i class="fa fa-linkedin"></i></a> </li>
  </ul>
</nav>

<center style="font-size:16px; margin-top:0px;">
  <i class="fa fa-clock-o"></i> Mis à jour le `r format(Sys.time(), '%d avril %Y')`

  <div style="margin-top:0px;">
  <i class="fa fa-user-o"></i> Jacob Taylor
  </div>
</center>

<link rel="icon" href="https://www.freefavicon.com/freefavicons/objects/jack-of-spades-152-192574.png">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">