---
title: "Gâteau Queen of Sheba"
author: "par Jacob Taylor"
date: "`r format(Sys.time(), '%d avril %Y')`"
output:
  prettydoc::html_pretty:
    theme: caymen
    css: style.css
    highlight: github
    math: katex
---
## Information

**Sert** : 8 personnes

**Durée de préparation** : 30m

**Durée totale** : 1h15m 

***

## Ingrédients

- 2/3 tasse de chocolat

- 2 cuillerée à soupe de rhum

- 1/2 tasse de beurre non-salé, à la température de la pièce

- 1/2 tasse de sucre et 2 cuillerée à soupe

- 3 jaunes d'oeufs

- 3 blancs d'oeufs

- 1/4 cuillerée à thé de crème de tarte

- 1 pincée de sel

- 1/3 tasse d'amandes blanchies (pulvérisées dans un mixeur avec 2 cuillerée à soupe de sucre)

- 1/4 cuillerée à thé d'extrait d'amande

- 1/2 tasse de farine à gâteau

***

## Préparation

1. Préchauffer le four à 350 degrées

2. Mettre la grille de four au bas du milieu

3. Faire chauffer de l'eau dans une casserole

4. Dans un bol, mélanger le chocolat et le rhum

5. Placer le bol sur la casserole jusqu'à ce que le chocolat soit fondu et lisse

6. Dans un bol à mélanger, couper le beurre en pièces et le crèmer

7. Lorsque le beurre est doux et mouelleux, ajouter le sucre et battre pour 1 minute

8. Ajouter et battre les jaunes d'oeufs jusqu'à ce que la préparation soit bien mélangé

9. Dans un autre bol, battre les blancs d'oeufs jusqu'à ce qu'ils deviennents mousseux

10. Ajouter la crème de tarte et le sel. Battre jusqu'à temps que le mélange se tienne

11. Ajouter graduellement les deux cuillerées à soupe de sucre pour obtenir un mélange lisse et brillant

12. Mélanger le chocolat fondu dans la préparation de jaune d'oeuf, suivi des amandes et de l'extrait d'amandes

13. Ajouter et mélanger le quart des blancs d'oeufs

14. Graduellement ajouter en alternant la farine et le reste des blancs d'oeufs

15. Mettre la préparation dans un moule à gâteau rond de 8 pouces qui a préalablement été beurré et fariné

16. Faire cuire pendant 25 minutes dans le four à 350 degrées

17. Sortir le gâteau et laisser reposer 15 minutes avant de l'enlever du moule

18. Laisser refroidir encore 2 heures avant de le glacer ou l'entrposer

***

<nav>
  <ul style="margin-bottom:0px;">
    <li> <a href="https://twitter.com/57JacobTaylor" target="_blank"><i class="fa fa-twitter" ></i></a> </li>
    <li><a href="https://www.instagram.com/jacobtaylorvsm/" target="_blank"><i class="fa fa-instagram" ></i></a> </li>
    <li><a href="https://open.spotify.com/user/31bygrnvenhfovhunk4mvtqdrht4?si=oXeg9RVfQZ2laUha4qXxhw" target="_blank"><i class="fa fa-spotify"></i></a> </li>
    <li><a href="https://github.com/jacobtaylor27" target="_blank"><i class="fa fa-github"></i> </a> </li>
    <li><a href="https://www.snapchat.com/add/jakkyboy27" target="_blank"><i class="fa fa-snapchat"></i></a> </li>
    <li><a href="https://www.reddit.com/user/jtaylor27/" target="_blank"><i class="fa fa-reddit"></i></a> </li>
    <li><a href="https://www.linkedin.com/in/jacob-t-1a570aba/" target="_blank"><i class="fa fa-linkedin"></i></a> </li>
  </ul>
</nav>

<center style="font-size:16px; margin-top:0px;">
  <i class="fa fa-clock-o"></i> Mis à jour le `r format(Sys.time(), '%d avril %Y')`

  <div style="margin-top:0px;">
  <i class="fa fa-user-o"></i> Jacob Taylor
  </div>
</center>

<link rel="icon" href="https://www.freefavicon.com/freefavicons/objects/jack-of-spades-152-192574.png">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

